---
- name: Ensure system is updated
  dnf:
    name: "*"
    state: latest

- name: Install PostgreSQL 15 repository
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Disable default PostgreSQL module
  command: dnf -qy module disable postgresql

- name: Install PostgreSQL 15 server
  dnf:
    name: postgresql15-server
    state: present

- name: Initialize PostgreSQL database
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  args:
    creates: /var/lib/pgsql/15/data/PG_VERSION

- name: Configure pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/15/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'

- name: Enable and start PostgreSQL service
  systemd:
    name: postgresql-15
    enabled: yes
    state: started

- name: Set PostgreSQL user password
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres
    password: "PostgreSQLPass"

- name: Create Semaphore user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "semaphore"
    password: "semaphorepass"
    encrypted: yes

- name: Create Semaphore database
  become: yes
  become_user: postgres
  postgresql_db:
    name: semaphoredb
    owner: semaphore
    encoding: UTF8
