---
- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Enable and start Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create SSL directory for Nginx
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Copy SSL certificate parameters file
  ansible.builtin.copy:
    src: ssl-info.txt
    dest: /etc/nginx/ssl/ssl-info.txt
    mode: '0644'

- name: Generate self-signed SSL certificate
  ansible.builtin.command:
    cmd: "openssl req -x509 -nodes -days 3652 -newkey rsa:2048 -keyout /etc/nginx/ssl/localhost.key -out /etc/nginx/ssl/localhost.crt -config /etc/nginx/ssl/ssl-info.txt"
  creates: /etc/nginx/ssl/localhost.crt

- name: Remove default Nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Copy Nginx Semaphore configuration
  ansible.builtin.copy:
    src: semaphore.conf
    dest: /etc/nginx/conf.d/semaphore.conf
    mode: '0644'

- name: Test Nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  register: nginx_test
  failed_when: "'nginx: configuration file' not in nginx_test.stderr"

- name: Reload Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
